Internationalize and use more of cjwmodule
CJWorkbench/transpose pull request #1
Opened 2020-02-10 12:42 UTC by giorgio93p

This pull request accomplishes two related tasks:

- internationalizes the warnings produced by this module, using the utils provided by `cjwmodule`
- uses a `cjwmodule` util that creates some (internationalized) warnings regarding column names

Notice: the corresponding changes to `cjwmodule` are still unpublished.

2020-02-15 10:11 UTC, giorgio93p commented
Depends on https://github.com/CJWorkbench/cjwmodule/pull/8

2020-02-18 16:22 UTC, adamhooper requested changes
Looking great. Just a few tweaks.

2020-02-18 16:22 UTC, adamhooper commented on test_transpose.py
> +                        "warnings.headersConvertedToText.error", {"column_name": "A"}
`.message`, not `.error`

2020-02-18 16:22 UTC, adamhooper commented on test_transpose.py
> +                                "warnings.headersConvertedToText.quick_fix.text",
(while we're editing stuff): `.quickFix`, not `.quick_fix`. (I don't have much of a preference of snake-case vs camel-case, but we shouldn't put both in the very same ID.)

2020-02-18 16:22 UTC, adamhooper commented on transpose.py
> +                    "warnings.differentColumnTypes.error",
`.message`

2020-02-18 16:22 UTC, adamhooper commented on transpose.py
> +                            "warnings.differentColumnTypes.quick_fix.text",
`.quickFix`

2020-02-18 16:22 UTC, adamhooper commented on transpose.py
> +        cols_str = ", ".join(f'"{c}"' for c in to_convert)
Let's not do this message formatting. It's not multilingual (and it doesn't even read properly in English.) Instead, please pass arguments `{n_columns}`, `{first_colname}`.

2020-02-18 22:03 UTC, adamhooper approved these changes

2020-02-18 22:03 UTC, merged